import {
  IconArrowRight,
  IconBrandFacebookFilled,
  IconBrandLinkedinFilled,
  IconBrandTwitterFilled,
  IconCalendarCheck,
  IconCaretDownFilled,
  IconCaretUpFilled,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconDeviceMobileFilled,
  IconMapPinFilled,
  IconMenu2,
  IconProps,
  IconToolsOff,
  IconUsers,
  IconX,
} from "@tabler/icons-react";

export const Icons = {
  Check: IconCheck,
  Down: IconCaretDownFilled,
  Up: IconCaretUpFilled,
  CalenderTick: IconCalendarCheck,
  PenTool: IconToolsOff,
  People: IconUsers,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ChevronUp: IconChevronUp,
  ChevronDown: IconChevronDown,
  ArrowRight: IconArrowRight,
  TwitterFilled: IconBrandTwitterFilled,
  FacebookFilled: IconBrandFacebookFilled,
  LinkedInFilled: IconBrandLinkedinFilled,
  Menu: IconMenu2,
  MapPin: IconMapPinFilled,
  PhoneFilled: IconDeviceMobileFilled,
  X: IconX,
};
type TIconKeys = keyof typeof Icons;

export type { TIconKeys, IconProps };
